name: The Bambui Resort

on:
  push:
    branches:
      - "main"
    
jobs:
  build:
    name: Docker Build Process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login to dockerhub
      - run: echo ${{secrets.DOCKER_HUB_PSSWD}} | docker login -u ${{secrets.DOCKER_HUB_USER}} --password-stdin
      - name: Build the dockerfile
      - run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USER}}/The-Bambui-Resort-img:latest
      - name: Docker push
      - run: docker push ${{secrets.DOCKER_HUB_USER}}/The-Bambui-Resort-img:latest